image: docker:20.10.11

services:
  - name: docker:20.10.11-dind
    alias: docker
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375 
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

# Docker
.docker_login: &docker_login
  before_script:
    - cat $CR_KEY | docker login -u json_key --password-stdin $CR_ADDR

.docker_build: &docker_build
  script:
    - docker pull $CR_ADDR/$CI_PROJECT_PATH:$LAST_IMAGE_TAG || true
    - docker build --cache-from $CR_ADDR:$LAST_IMAGE_TAG -t $CR_ADDR/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME -t $CR_ADDR/$CI_PROJECT_PATH:$LAST_IMAGE_TAG .
    - docker push $CR_ADDR/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
    - docker push $CR_ADDR/$CI_PROJECT_PATH:$LAST_IMAGE_TAG

# Tag Restrictions
.restrictions_dev: &restrictions_dev
  only:
    refs:
      - tags
    variables:
      - $CI_BUILD_REF_NAME =~ /^\d+\.\d+\.\d+$/

.restrictions_stage-prod: &restrictions_stage-prod
  only:
    refs:
      - tags
    variables:
      - $CI_BUILD_REF_NAME =~ /^\d+\.\d+\.\d+\-stage-prod$/

.restrictions_prod: &restrictions_prod
  only:
    refs:
      - tags
    variables:
      - $CI_BUILD_REF_NAME =~ /^\d+\.\d+\.\d+\-prod$/

# Stage Build
build_dev:
  stage: build
  <<: *restrictions_dev
  <<: *docker_login
  <<: *docker_build
  variables:
    LAST_IMAGE_TAG: latest

build_stage-prod:
  stage: build
  <<: *restrictions_stage-prod
  <<: *docker_login
  <<: *docker_build
  variables:
    LAST_IMAGE_TAG: latest-stage-prod

# Deploy 2 ArgoCD
deploy_dev:
  stage: deploy
  <<: *restrictions_dev
  image: cr.yandex/crpe5nlmt14r7sp5papq/devops/infrastructure:1.0.0-argocd
  script:
    -  argocd login $ARGOCD_DEV_ADDR --username admin --password $ARGOCD_DEV_PASS --grpc-web
    -  argocd app set $CI_PROJECT_NAME -p image.tag=$CI_BUILD_REF_NAME --grpc-web
    -  argocd app sync $CI_PROJECT_NAME

deploy_stage:
  stage: deploy
  <<: *restrictions_stage-prod
  image: cr.yandex/crpe5nlmt14r7sp5papq/devops/infrastructure:1.0.0-argocd
  script:
    -  argocd login $ARGOCD_STAGE_ADDR --username admin --password $ARGOCD_STAGE_PASS --grpc-web
    -  argocd app set $CI_PROJECT_NAME -p image.tag=$CI_BUILD_REF_NAME --grpc-web
    -  argocd app sync $CI_PROJECT_NAME

deploy_prod:
  stage: deploy
  <<: *restrictions_prod
  image: cr.yandex/crpe5nlmt14r7sp5papq/devops/infrastructure:1.0.0-argocd
  before_script:
    -  VERSION=$(echo $CI_BUILD_REF_NAME | cut -d '-' -f1)-stage-prod
  script:
    -  argocd login $ARGOCD_PROD_ADDR --username admin --password $ARGOCD_PROD_PASS --grpc-web
    -  argocd app set $CI_PROJECT_NAME -p image.tag=$VERSION --grpc-web
    -  argocd app sync $CI_PROJECT_NAME
