replicaCount: 1

image:
  repository: cr.yandex/crp5ufj07k4l2safqpve/agency/lottery/spa-lottery
  tag: latest-prod
  pullPolicy: IfNotPresent
  
imagePullSecrets:
  - name: regcred

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    ingress.alb.yc.io/subnets: "e9bgq48t1ov6a0t3nhf2"
    ingress.alb.yc.io/external-ipv4-address: "178.154.220.39"
    ingress.alb.yc.io/group-name: "rba-lottery-prod"
  hosts:
    - host: 'spa.lottery.plat.agency'
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: 'yc-certmgr-cert-id-fpqkgsg1t08hd53o07h2'
      hosts:
        - 'spa.lottery.plat.agency'
        
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configEnvs:
  SPA_BASE_URL: "https://spa.lottery.plat.agency"
  CMS_BASE_URL: "https://cms.lottery.plat.agency"
  PORT: 80
  NODE_ENV: "production"
